### ISSUE TITLE
Issue with JSON parsing

### ISSUE THREAD

**Issue by johnsaigle** [droposhado/apple-notes-exporter#1]
Hi! This script is a great start and I hope you continue to develop it.

When I ran the script, I got the following:
```bash
> make                                                                                                
osascript notes.applescript > notes.txt
rm -rf dist
mkdir dist
python3 notes.py notes.txt
Traceback (most recent call last):
  File "/.../apple-notes-exporter/notes.py", line 56, in <module>
    "creation_date": get_datetime_string(note_creation_date),
  File "/.../apple-notes-exporter/notes.py", line 20, in get_datetime_string
    dt_obj = datetime.strptime(string, DATETIME_IMPORT_MASK)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Tuesday, June 14, 2016 at 21:55:08' does not match format '%A, %B %d, %Y at %I:%M:%S %p'
make: *** [json] Error 1
```

It looks like the failing note is using 24h time so it is missing the `%p` format from `DATETIME_IMPORT_MASK`

**Comment by droposhado** [comment]
Sorry for the delay and thank you very much, I'm glad this is the first one I get from a project I've done.

Thank you very much
